# Generated by Django 4.0.3 on 2022-04-11 10:19

import django.core.validators
from django.db import migrations, models
import django_backend.drf_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django_backend.drf_api.models.validate_color])),
            ],
        ),
    ]
